#!/bin/bash

# Convert image assets to memory initialization files
util/png_to_mif --output=p1_sprites.mif --depth=2 --xywidth=8 --offset=0 assets/p1_stand.png assets/p1_stand_attack.png assets/p1_jump_attack.png
util/png_to_mif --output=p2_sprites.mif --depth=2 --xywidth=8 --offset=0 assets/p2_stand.png assets/p2_stand_attack.png assets/p2_jump_attack.png
